---
- name: Satellite server configuration playbook
  hosts: ipaserver,ipaclients
  become: true
  tasks:
    - name: Set idm-server IP fact
      ansible.builtin.set_fact:
        idm_server_ip: "{{ hostvars[groups['ipaserver'][0]]['ansible_default_ipv4']['address'] }}"

- name: Playbook to configure IPA servers
  hosts: ipaserver
  become: true
  collections:
    - freeipa.ansible_freeipa

  pre_tasks:
    - name: Register system with Red Hat Subscription Manager
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id | default(omit, true) }}"

    - name: Ensure all packages are updated
      ansible.builtin.dnf:
        name: '*'
        state: latest # noqa package-latest

  roles:
  - role: freeipa.ansible_freeipa.ipaserver
    state: present

- name: Playbook to configure ipaclients to use ipa-server as DNS
  hosts: ipaclients
  become: true
  tasks:
    - name: Set DNS to idm-server
      ansible.builtin.shell: nmcli con mod ens3 ipv4.dns {{ hostvars[inventory_hostname].idm_server_ip }}

    - name: Restart NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

