- name: This play downloads required ISOs for VM setup
  hosts: localhost
  tasks:
    - name: Include downloader role
      ansible.builtin.include_role:
        name: package-downloader
      vars:
        rh_product_filename: "{{ item.filename }}"
        rh_product_name: "{{ item.product }}"
        rh_api_offline_token: "{{ offline_token }}"
      loop:
        - filename: rhel9.iso
          product: "rhel9"
      when:
        - offline_token is defined
        - offline_token != ""

- name: This play provisions VMs for IDM Lab
  hosts: localhost
  become: true
  tasks:
    - name: Provision libvirt VM using role
      ansible.builtin.include_role:
        name: host-provisioner
      vars:
        host_modules: "{{ modules }}"
        host_domain: "{{ domain }}"
        host_tf_vars:
          network_cidr: ' ["{{ network_cidr }}"]'

    - name: Ensure to clean known_hosts
      ansible.builtin.known_hosts:
        host: "{{ item.hostname }}.{{ domain }}"
        path: ~/.ssh/known_hosts
        state: absent
      loop: "{{ modules }}"
      become: false

- name: Check connection to servers
  hosts: ipa_server,ipa_clients
  gather_facts: false
  tasks:
    - name: Waiting for installation to end, it can take time!
      ansible.builtin.wait_for_connection:
        timeout: 1800
        delay: 600

    - name: Ping host to check status
      ansible.builtin.ping:

    - name: Setup is ready
      ansible.builtin.debug:
        msg: "Setup completed, now you can proceed with post install steps"
