---
collections:
- community.general
- ansible.posix
- freeipa.ansible_freeipa

roles:
- name: package-downloader
  src: https://github.com/kubealex/role-package-downloader
- name: host-provisioner
  src: https://github.com/kubealex/role-host-provisioner
